### ISSUE TITLE
How to save training parameters for direct prediction

### ISSUE THREAD

**Issue by shushan2017** [ChangWeiTan/MultiRocket#10]
This is a great model because real-time training consumes more time and memory. I want to call it directly when I use it, such as 
1 train (x) -- save (model) 
 2 load (model) -- prediction (test)

Thank you.

**Comment by ChangWeiTan** [comment]
Hi @shushan2017 , apologies for the super late reply. I did not check the issues here. 

An easy way is to dump the whole object into a pickle file.

**Comment by llhww** [comment]
Did you succeed? I keep getting an error after saving pickle.
