### ISSUE TITLE
Are the results for all 30 resamples available?

### ISSUE THREAD

**Issue by jcoll3** [ChangWeiTan/MultiRocket#11]
I'm running a large number of model variants over a subset of the folds, and it would help with comparison. Thanks!

**Comment by ChangWeiTan** [comment]
Hi @jcoll3, apologies for the delay in response. I did not check the issues here. Somehow when I first pushed the code, the resample results for each fold were not included. I have now pushed them in the results folder. Hope that it will still help you.
