### ISSUE TITLE
about parameters

### ISSUE THREAD

**Issue by FUNKYQ** [ChangWeiTan/MultiRocket#12]
It is a good model, but now I have a problem, if i have got too much data, what parameters can I adjust to fasten the training. I have got a data (80000,3000) which cost too much memory and trained very slowly. How can I fix it? Thanks a lot.

**Comment by ChangWeiTan** [comment]
Hi @FUNKYQ , sorry for the late response! I have not checked the issues here. Currently, the only way I know is to transform the data in chunks. Have a look at the minirocket implementation by Angus (https://github.com/angus924/minirocket/blob/main/code/softmax.py) and TSAI (https://github.com/timeseriesAI/tsai/blob/main/tsai/models/MINIROCKET.py). I have not implemented this for Multirocket yet.
