### ISSUE TITLE
Normalise feature

### ISSUE THREAD

**Issue by YunruiZhang** [ChangWeiTan/MultiRocket#13]
Hi, 

I found that in multi-rocket the features are not normalized when fed into the ridge classifier, While they are normalized in rocket and mini-rocket.  Is this due to the MPV and MIPV could be -1 or is there any other reason behind this? I wonder if the normalized features have any effect on the performance. 

Thank you in advance.
Yunrui

**Comment by ChangWeiTan** [comment]
Hi, the features have always been normalised. Internally in sklearn Ridge classifier (before the update), the features are normalised with the normalise parameter.
