### ISSUE TITLE
109 or 119 datasets?

### ISSUE THREAD

**Issue by firrice** [ChangWeiTan/MultiRocket#16]
hi, I found you do experiments on 109 problems in paper. But i find there have been the result of 112 problems, for 30 resamples in http://timeseriesclassification.com/results.php. So i wonder why you choose do experiments on 109 datasets rather than 112? Is that due to the reason which there was only the result of 109 peoblems in timeseriesclassification.com at the moment? or other reasons?

**Comment by ChangWeiTan** [comment]
Hi, its 109 following the typical benchmark done on timeseriesclassification.com on other approaches. I provided 112 results as I was able to run them all.
