### ISSUE TITLE
MultiRocket performance on multivariate timeseries

### ISSUE THREAD

**Issue by rubbiyasultan** [ChangWeiTan/MultiRocket#17]
Have you tried running multirocket on multivariate time series having more that 1000 samples, like in LSST or InsectWingbeat? For me, your code doesn't run on InsectWingBeat. The model seems to be overfitting because it gives high train accuracy (comparable to minirocket) but very low-test accuracy.

**Comment by ChangWeiTan** [comment]
Hi, Yes I did run it on LSST and InsectWingbeat before. Perhaps you need a bigger ram size or try running it with logistic regression. I agree that the model can overfit quite easily.
