### ISSUE TITLE
TypeError: No matching definition for argument type(s) array

### ISSUE THREAD

**Issue by Huii** [ChangWeiTan/MultiRocket#2]
First of all: Thank you very much for this project and providing the code online. :)

Unfortunately, I'm not able to get it to run properly and always run into an error message stemming from a call to the function _fit_biases_ in the "fit" method of minirocket_multivariate.py. This is how I call the method:

```
    print(X.dtype)
    print(X.shape)
    print(num_channels_per_combination.dtype)
    print(num_channels_per_combination.shape)
    print(channel_indices.dtype)
    print(channel_indices.shape)
    print(dilations.dtype)
    print(dilations.shape)
    print(num_features_per_dilation.dtype)
    print(num_features_per_dilation.shape)
    print(quantiles.dtype)
    print(quantiles.shape)
    
    biases = _fit_biases(X, num_channels_per_combination, channel_indices, dilations, num_features_per_dilation, quantiles)
```

And this is the output I receive:

```
[MiniRocket_202_10000] Training with training set of (5190, 2048)
float64
(5190, 2048)
int32
(2184,)
int32
(7417,)
int32
(26,)
int32
(26,)
float64
(4956,)
Traceback (most recent call last):
[...]
TypeError: No matching definition for argument type(s) array(float64, 2d, C), array(int32, 1d, C), array(int32, 1d, C), array(int32, 1d, C), array(int32, 1d, C), array(float64, 1d, C)
```

I had[ a similar issue](https://github.com/angus924/minirocket/issues/1) with MINIROCKET, which could be solved by changing the njit signatures as described by @angus924. Unfortunately, changing the signatures does not work in this case. Any help is highly appreciated.

**Comment by angus924** [comment]
Hi @Huii, it looks like your input, `X`, is `np.float64`, when it should be `np.float32`.  Could you try casting both your training and test data, e.g.:

```python
X_training = X_training.astype(np.float32)
X_test = X_test.astype(np.float32)
```

Shouldn't need to do anything with the signatures, so try doing this just with the original signatures, and just using the `fit` function rather than `_fit_biases`.  All floats should be `np.float32`, including quantiles.

Let us know if this fixes the issue (or doesn't...).

**Comment by Huii** [comment]
Hi @angus924 (you're everywhere, arent't you? ;-) ),

My bad, I forgot to mention that I actually already changed the signature in an (futile) attempt to mitigate the problem. My signature right before the "_fit_biases" function looks as follows:

`@njit("float64[:](float64[:,:,:],int32[:],int32[:],int32[:],int32[:],float64[:])", fastmath=True, parallel=False, cache=True)`

//edit: I just tried to keep the original signatures and only cast the input as you suggested but I keep getting the same error (with float32 instead of float64 this time).

**Comment by angus924** [comment]
Thanks @Huii.

Would you be able to provide a bit more of your output (as much as possible really), so that we can see the exact error?  The error shouldn't be the same after casting the input (I'm not disputing that there's an error, but it should be a different error...).


(Via email would also be fine if you prefer.)

Thanks.

**Comment by ChangWeiTan** [comment]
Hi @Huii , It would be great if you could provide a snippet of your code. If you change the signature of _fit_biases, then you should also change the signature for transform. By default, in the main files, I have cast all inputs to float32 if minirocket kernels were to be used (although this will be standardised in the future) and it should work straight out of the box if you run one of the main files. Another possible reason is that maybe the cache is not updated. I had similar issues with it before. One way is to run the program without caching and cache again so that the cache is updated.

**Comment by Huii** [comment]
Thank you both very much for your help.

I decided to try everything again by purging all my changes to your code and cloning the whole repo again. I would also like to provide a small glimpse into my data to help with further investigations.

This is how I call your functions from my code wrapper:

```
def performMultiRocketForMyData(x_trainScaled,x_testScaled,y_train,y_test,pathToResults,modelName):
    x_trainScaled = np.array(x_trainScaled).astype(np.float32)
    x_testScaled = np.array(x_testScaled).astype(np.float32)

    x_trainScaled = x_trainScaled[1:3]
    x_testScaled = x_testScaled[1:3]
    y_train = y_train[1:3]
    y_test = y_test[1:3]
    
    print(x_trainScaled)
    print(x_testScaled)
    print(y_train)
    print(y_test)
    
    itr = 0
    kernel_selection = 0
    num_features = 10000
    feature_id = 202
    save = False
    num_threads = 0

    nb_classes = len(np.unique(np.concatenate((y_train, y_test), axis=0)))
    classifier = MultiRocket(num_features=num_features, feature_id=feature_id,kernel_selection=kernel_selection)
    yhat_train = classifier.fit(x_trainScaled, y_train, predict_on_train=False)
```
The output is:
```
[[  3.   1.  -8. ...  23.  35.  -4.]
 [ -4.  -3.  13. ...   8.  21. -54.]]
[[-10.   3.   4. ...  -6.  13.  10.]
 [ -5.  -8.   4. ... -17.  -5.  21.]]
[0, 0]
[0, 0]
FeatureID: 202 -- features for each kernel: ['PPV', 'CO_HistogramAMI_even_2_5', 'SB_BinaryStats_mean_longstretch1', 'SB_MotifThree_quantile_hh', 'LongStretch_above_0', 'Max']
Creating MiniRocket_202_10000 with 5000 kernels
[MiniRocket_202_10000] Training with training set of (2, 2048)
Traceback (most recent call last):
  [...]
 MultiRocket.performMultiRocketForMyData(X_trainScaled,X_testScaled,Y_train,Y_test,pathToResults,modelName)
  File "PathTo\MultiRocket.py", line 35, in performMultiRocketForMuscleData
    yhat_train = classifier.fit(x_trainScaled, y_train, predict_on_train=False)
  File "PathTo\MultiRocket\multirocket\multirocket.py", line 71, in fit
    num_features=self.num_kernels)
  File "PathTo\MultiRocket\multirocket\minirocket_multivariate.py", line 136, in fit
    _, num_channels, input_length = X.shape
ValueError: not enough values to unpack (expected 3, got 2)
```

To get rid of this error, I remove the "_", ending up with the following line as first line in the "fit" function:
`num_channels, input_length = X.shape`

Now, everything works fine until I end up with this error again:
```
FeatureID: 202 -- features for each kernel: ['PPV', 'CO_HistogramAMI_even_2_5', 'SB_BinaryStats_mean_longstretch1', 'SB_MotifThree_quantile_hh', 'LongStretch_above_0', 'Max']
Creating MiniRocket_202_10000 with 5000 kernels
[MiniRocket_202_10000] Training with training set of (2, 2048)
Traceback (most recent call last):
 [...]
MultiRocket.performMultiRocketForMyData(X_trainScaled,X_testScaled,Y_train,Y_test,pathToResults,modelName)
  File "PathTo\MultiRocket.py", line 35, in performMultiRocketForMuscleData
    yhat_train = classifier.fit(x_trainScaled, y_train, predict_on_train=False)
  File "PathTo\MultiRocket\multirocket\multirocket.py", line 71, in fit
    num_features=self.num_kernels)
  File "PathTo\MultiRocket\multirocket\minirocket_multivariate.py", line 167, in fit
    quantiles)
  File "PathToPython\Python37\site-packages\numba\core\dispatcher.py", line 646, in _explain_matching_error
    raise TypeError(msg)
TypeError: No matching definition for argument type(s) array(float32, 2d, C), array(int32, 1d, C), array(int32, 1d, C), array(int32, 1d, C), array(int32, 1d, C), array(float32, 1d, C)
```

Unfortunately, this also happens if I set the "cache" parameters to "False" in the signatures of "_fit_biases" and "transform".

Please let my know if you need any further details. I also hope the snippet of my input signals is enough for further investigations. If not, just let me know and I can try to share some complete input arrays with you.

**Comment by ChangWeiTan** [comment]
@Huii, This seems like a mismatch between dimensions. In the minirocket_multivariate.py, the functions expect the data to be in 3 dims, i.e. (num_instances, num_channel, ts_length). If your data is univariate, I suggest to reshape it to (num_instances, 1, ts_length). By the way I have just updated the repo with some minor bug fix as well. Please have another go. Thanks!

**Comment by Huii** [comment]
Thank you very much! That did the trick for me. :-) I have another question but will post it as a separate issue to keep things in order.

**Comment by ChangWeiTan** [comment]
Awesome! Curious to see how they perform on your data. If there is no further issue with this, I will close this.
