### ISSUE TITLE
ValueError: empty range for randrange()

### ISSUE THREAD

**Issue by Huii** [ChangWeiTan/MultiRocket#5]
Hello again,

Once again I'm having a small issue with MultiRocket. I'm currently attempting to run it with ROCKET instead of MINIROCKET kernels in order to compare the results.

This is how I call the MultiRocket functions from my wrapper:

```
    x_trainScaled = np.array(x_trainScaled).astype(np.float32)
    x_testScaled = np.array(x_testScaled).astype(np.float32)

    itr = 0
    kernel_selection = 1
    x_trainScaled = x_trainScaled.reshape((len(x_trainScaled),1,len(x_trainScaled[0])))
    x_testScaled = x_testScaled.reshape((len(x_testScaled),1,len(x_testScaled[0]))
    num_features = 10000
    feature_id = 202
    save = False
    num_threads = 0

    nb_classes = len(np.unique(np.concatenate((y_train, y_test), axis=0)))
    classifier = MultiRocket(num_features=num_features, feature_id=feature_id,kernel_selection=kernel_selection)
    yhat_train = classifier.fit(x_trainScaled, y_train, predict_on_train=False)
```

This is the error I end up with:

```
Traceback (most recent call last):
  File "PathTo\MultiRocket\multirocket\multirocket.py", line 81, in fit
    self.kernels = rocket.generate_kernels(x_train.shape[1],
ValueError: empty range for randrange()
```

This is how my data looks like:

```
x_trainScaled = x_trainScaled[1:3]
x_testScaled = x_testScaled[1:3]
y_train = y_train[1:3]
y_test = y_test[1:3]
     
print(x_trainScaled)
print(x_testScaled)
print(y_train)
print(y_test)

[[ 0.7447274   0.06916068 -0.682534   ... -1.6474844   0.14956714
   0.67884177]
 [-0.45166248  0.63615835  0.63785297 ... -1.9533293  -1.9626789
  -0.8409533 ]]
[[-0.44333452  0.6645574   0.61655885 ... -0.75293815 -0.80983204
  -1.764199  ]
 [-0.65810275  0.64497143  0.79669493 ... -0.75293815 -0.4981184
  -0.22035763]]
[0, 0]
[0, 0]
```

Any help is highly appreciated!

**Comment by ChangWeiTan** [comment]
Hi @Huii, for Multirocket, the input data should be channel last, i.e. (num_examples, ts_length, **num_channels**). Currently rocket functions take in data in this format while minirocket functions take in data in (num_examples, **num_channels**, ts_length) format. This is currently being handled internally in the Multirocket class as long as you pass in the data with channel last. I understand that this can be confusing and my next update to the repo will attempt to fix this.

**Comment by Huii** [comment]
Hello @ChangWeiTan,

Thank you very much, that did the trick for me! Strangely, I got a numba error again as I cast my data to float32. However, leaving it as float64 arrays, allows me to run MulitRocket with ROCKET kernels.

Keep up the good work and have a nice weekend. :)

**Comment by ChangWeiTan** [comment]
Hi @Huii , Yes as of now, Rocket kernels use float64. but Minirocket kernels use float32. I understand that it is not ideal and will be updated in my future update to the repo.  Hope that these help with your problem, curious to know how they performed. Let me know if you have anymore issues. :)
