### ISSUE TITLE
sktime.utils.load_data error

### ISSUE THREAD

**Issue by Frazetti** [ChangWeiTan/MultiRocket#8]
Hello,
I am currently working with one of Your files, main_mtsc.py with versions:
Python 3.8.5
sktime 0.5.3

Running script resulted in error message:
ModuleNotFoundError: No module named 'sktime.utils.load_data'

Switching 'load_data' to suggested in current sktime documentation 'data_io' seems to resolve the problem :)

**Comment by ChangWeiTan** [comment]
Thanks for this. :) Will fix that.
